name: CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 23.3.0
            
            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test
            
            - name: Build for web
              run: npx expo export

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: web-build
                path: dist/
    
    deploy:
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Download build artifacts
              uses: actions/download-artifact@v3
              with:
                name: web-build

            - name: Deploy on GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist